project_id = "kamtarwxydftzpewcgzs"

[functions.create-test-users]
verify_jwt = false

[functions.invite-employee]
verify_jwt = false

[functions.send-activation-email]
verify_jwt = false

[functions.activate-account]
verify_jwt = false