// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kamtarwxydftzpewcgzs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImthbXRhcnd4eWRmdHpwZXdjZ3pzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE4MjAzNjQsImV4cCI6MjA3NzM5NjM2NH0.bqeDHG_PBAZmg8Y4Uc264qOTpCPIfBocpjkiZjn9u6s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});